<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaVenta.BLL\SistemaVenta.BLL.csproj" />
    <ProjectReference Include="..\SistemaVenta.Entity\SistemaVenta.Entity.csproj" />
    <ProjectReference Include="..\SistemaVenta.IOC\SistemaVenta.IOC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Utilidades\LibreriaPDF\libwkhtmltox.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Utilidades\LibreriaPDF\libwkhtmltox.dylib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Utilidades\LibreriaPDF\libwkhtmltox.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\imagenes\logos\" />
    <Folder Include="wwwroot\imagenes\usuarios\" />
    <Folder Include="wwwroot\imagenes\productos\" />
  </ItemGroup>

</Project>
